### ISSUE TITLE
Etusivun rakenne

### ISSUE THREAD

**Issue by ttsirkia** [finnishtransportagency/digitraffic#2]
Vähän hassua että ensimmäisenä on statukset ja linkit statussivuille ja vasta alempana linkit itse rajapintoihin. Voisikohan noita jotenkin yhdistää niin, että heti alussa olisi jo rajapintalinkki että myös itse statuskuvaus?

Vaikka olisi sitten alla pidemmätkin tekstit, niin on epäloogista, että statuslinkit on nähty tärkeämmiksi kuin itse rajapintakuvaukset.

https://github.com/finnishtransportagency/digitraffic/blob/ad9a1747e953f0aa5957cce89ffcb3f30f013053/_layouts/frontpage.html#L40

**Comment by jaakko-solita** [comment]
Korjasin tämän ennen julkaisua
