### ISSUE TITLE
Saman otsikon käyttäminen useasti rikkoo sisällysluettelon linkitykset

### ISSUE THREAD

**Issue by petja** [finnishtransportagency/digitraffic#3]
Samaa väliotsikkoa käytetään useassa eri kohdassa [rautatieliikennettä koskevalla sivulla](/finnishtransportagency/digitraffic/blob/master/pages/rata/rautatieliikenne.md), joka aiheuttaa sen että sisällysluettelon linkit voivat johtaa väärään kohtaan sivua niitä klikatessa.

Esimerkiksi otsikko `Kaikkien junien seuranta` ja sitä vastaava URL fragment `#kaikkien-junien-seuranta` esiintyy sivulla kahden eri pääotsikon alla:
* Junien tiedot (/trains)
* Tarkempi seuranta kulkutietoviestien avulla (/train-tracking)

Näin ollen sisällysluettelossa kun klikkaan `Tarkempi seuranta kulkutietoviestien avulla (/train-tracking)` alta kyseistä väliotsikkoa, heittää selain minut otsikon `Junien tiedot (/trains)` alle. Tämä ehti aiheuttaa minulle jo kertaalleen hieman hämmennystä.

Tälle ongelmalle ei liene voi tehdä juurikaan mitään muuta kuin miettiä otsikot uusiksi, tai vaihtoehtoisesti harkita tiedon palastelua useammalle eri sivulle, joka voisi muutenkin selkeyttää dokumentaation lukemista.

Kiitokset etukäteen!

**Comment by jaakko-solita** [comment]
Pahoittelut, tämä oli jäänyt huomaamatta. Pitää käydä asettamassa vipu, että näistä saa sähköpostin.

Kiitoksia ilmoituksesta. Korjasin ongelman miettimällä otsikoita hieman uusiksi: https://github.com/finnishtransportagency/digitraffic/commit/42d145abe987e92f4ea654b4456f96177fe10eaf
